// filepath: apps/frontend/components/features/dashboard/ExportReportButton.tsx

"use client";

import { useState } from "react";
import { DashboardStats } from "@/features/dashboard/api";

type ExportReportButtonProps = {
    stats: DashboardStats;
    email: string;
};

export default function ExportReportButton({ stats, email }: ExportReportButtonProps) {
    const [loading, setLoading] = useState(false);

    const handleExport = async () => {
        setLoading(true);
        try {
            // ✅ Generate formatted text report (no PDF renderer needed)
            const reportText = generateReportText(stats, email);

            // ✅ Create Blob and trigger download
            const blob = new Blob([reportText], { type: "text/plain;charset=utf-8" });
            const url = URL.createObjectURL(blob);
            const link = document.createElement("a");
            link.href = url;
            link.download = `dashboard-report-${new Date().toISOString().split("T")[0]}.txt`;
            document.body.appendChild(link);
            link.click();

            // ✅ Cleanup
            document.body.removeChild(link);
            URL.revokeObjectURL(url);

        } catch (error) {
            console.error("Failed to export report:", error);
            alert("Failed to export report. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    // ✅ Helper: Format stats into readable text report
    const generateReportText = (stats: DashboardStats, email: string): string => {
        // ✅ Priority order for application statuses (most positive first)
        const STATUS_PRIORITY = ["offer", "interview", "oa", "applied", "rejected"];

        const lines = [
            "═══════════════════════════════════════",
            "   CAREERFORGE DASHBOARD REPORT",
            "═══════════════════════════════════════",
            `Generated: ${new Date().toLocaleString()}`,
            `User: ${email || "N/A"}`,
            "",
            "📊 APPLICATION TRACKING",
            "───────────────────────────────────────",
            `Total Applications: ${stats.applications}`,
            `Success Rate (Offers): ${stats.applicationSuccessRate}%`,
            `Status Breakdown:`,
        ];

        // ✅ Sort statuses by priority before rendering
        const sortedStatuses = Object.entries(stats.applicationBreakdown || {})
            .filter(([_, count]) => count > 0)
            .sort((a, b) => {
                const [statusA, statusB] = [a[0], b[0]];
                const priorityA = STATUS_PRIORITY.indexOf(statusA);
                const priorityB = STATUS_PRIORITY.indexOf(statusB);

                if (priorityA !== -1 && priorityB !== -1) return priorityA - priorityB;
                if (priorityA !== -1) return -1;
                if (priorityB !== -1) return 1;
                return statusA.localeCompare(statusB);
            });

        sortedStatuses.forEach(([status, count]) => {
            lines.push(`  • ${status.charAt(0).toUpperCase() + status.slice(1)}: ${count}`);
        });

        lines.push(
            "",
            "💻 DSA PROGRESS",
            "───────────────────────────────────────",
            `Problems Solved: ${stats.dsaSolved}`,
            `Total Problems: ${stats.dsaTotal}`,
            `Completion Rate: ${stats.dsaSuccessRate}%`,
            `Progress Details:`,
            `  • Completed: ${stats.dsaProgress.completed}`,
            `  • In Progress: ${stats.dsaProgress.inProgress}`,
            `  • Remaining: ${stats.dsaProgress.notStarted}`,
            "",
            "═══════════════════════════════════════",
            "Generated by CareerForge AI",
            "For personal tracking only",
            "═══════════════════════════════════════"
        );

        return lines.join("\n");
    };

    return (
        <button
            onClick={handleExport}
            disabled={loading}
            className="px-4 py-2 text-sm bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-lg flex items-center gap-2 transition-colors"
        >
            {loading ? "Exporting..." : "📥 Export Report"}
        </button>
    );
}