import jsPDF from "jspdf";
import { ResumeAnalysis } from "@/types/resume";
import { JDMatch } from "@/types/jd";

// PDF Configuration Constants
const MARGIN = 15;
const CONTENT_WIDTH = 180; // A4 width (210mm) - 2*MARGIN
const PAGE_HEIGHT = 297;   // A4 height in mm
const FOOTER_Y = 290;      // Footer position from top

// ✅ Sanitize filename for all OS (Windows, macOS, Linux)
const sanitizeFilename = (filename: string): string => {
  return filename
    .replace(/[<>:"/\\|?*]/g, "_")  // Remove invalid chars
    .replace(/\s+/g, "_")            // Normalize whitespace
    .slice(0, 100);                  // Prevent overly long filenames
};

// ✅ Helper: Add footer to CURRENT page only
const addFooter = (doc: jsPDF) => {
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(150);
  doc.text("Generated by CareerForge AI Tracker • Confidential", MARGIN, FOOTER_Y);
};

// ✅ Helper: Safe text wrapper with proper page-break handling
const addWrappedText = (
  doc: jsPDF, 
  yRef: { current: number }, 
  text: string | undefined | null, 
  fontSize: number = 10, 
  color: [number, number, number] = [50, 50, 50], 
  bold = false
) => {
  if (!text || !text.trim()) return;
  
  doc.setFont("helvetica", bold ? "bold" : "normal");
  doc.setFontSize(fontSize);
  doc.setTextColor(...color);
  
  const lines = doc.splitTextToSize(text.trim(), CONTENT_WIDTH);
  
  for (const line of lines) {
    // Check if we need a new page BEFORE writing
    if (yRef.current > 270) {
      doc.addPage();
      yRef.current = 20; // Reset Y for new page
    }
    doc.text(line, MARGIN, yRef.current);
    yRef.current += fontSize * 0.6 + 2;
  }
  yRef.current += 4; // Extra spacing after block
};

// ✅ Helper: Section title with optional subtitle + page-break safety
const addSectionTitle = (
  doc: jsPDF, 
  yRef: { current: number }, 
  title: string, 
  subtitle?: string
) => {
  // Ensure space for title + subtitle
  if (yRef.current > 250) {
    doc.addPage();
    yRef.current = 20;
  }
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(37, 99, 235); // blue-600
  doc.text(title, MARGIN, yRef.current);
  yRef.current += 6;
  
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(subtitle, MARGIN, yRef.current);
    yRef.current += 8;
  } else {
    yRef.current += 4;
  }
};

// ✅ Helper: Bullet list with page-break safety
const addBulletList = (
  doc: jsPDF, 
  yRef: { current: number }, 
  items: string[] | undefined | null
) => {
  if (!items || !items.length) return;
  
  items.forEach((item) => {
    // Check page break before each bullet
    if (yRef.current > 270) {
      doc.addPage();
      yRef.current = 20;
    }
    const text = `• ${item}`;
    addWrappedText(doc, yRef, text, 10, [50, 50, 50]);
  });
  yRef.current += 4;
};

// ✅ RESUME ANALYSIS PDF GENERATOR (Fixed)
export const generateResumeAnalysisPDF = (data: ResumeAnalysis) => {
  try {
    // ✅ LOCAL state - no module-level mutation
    const doc = new jsPDF();
    const y = { current: 20 }; // Use object ref for mutable Y position

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(17, 24, 39);
    doc.text("Resume ATS Analysis Report", MARGIN, y.current);
    y.current += 10;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated: ${new Date().toISOString().split("T")[0]} | File: ${data.originalFilename}`, MARGIN, y.current);
    y.current += 6;
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const scoreColor = data.aiScore >= 80 ? [22, 163, 74] : data.aiScore >= 60 ? [202, 138, 4] : [220, 38, 38];
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(`Overall Score: ${data.aiScore}/100`, MARGIN, y.current);
    y.current += 14;

    // Sections
    addSectionTitle(doc, y, "Executive Summary");
    addWrappedText(doc, y, data.overall_summary);

    addSectionTitle(doc, y, "ATS Compatibility", `Score: ${data.feedback.ats_compatibility.score}/100`);
    addWrappedText(doc, y, data.feedback.ats_compatibility.feedback);

    addSectionTitle(doc, y, "Skills Alignment", `Score: ${data.feedback.skills_match.score}/100`);
    if (data.feedback.skills_match.missing?.length) {
      addWrappedText(doc, y, `Missing Keywords: ${data.feedback.skills_match.missing.join(", ")}`, 10, [220, 38, 38]);
    }
    if (data.feedback.skills_match.suggestions?.length) {
      addBulletList(doc, y, data.feedback.skills_match.suggestions);
    }

    addSectionTitle(doc, y, "Formatting Review", `Score: ${data.feedback.formatting.score}/100`);
    if (data.feedback.formatting.issues?.length) {
      addBulletList(doc, y, data.feedback.formatting.issues);
    } else {
      addWrappedText(doc, y, "No major formatting issues detected.", 10, [22, 163, 74]);
    }

    addSectionTitle(doc, y, "Keyword Analysis");
    addWrappedText(doc, y, `Found: ${data.feedback.keywords.found?.slice(0, 6).join(", ") || "None"}`);
    addWrappedText(doc, y, `Missing: ${data.feedback.keywords.missing?.slice(0, 6).join(", ") || "None"}`);

    addSectionTitle(doc, y, "Actionable Steps");
    addBulletList(doc, y, data.actionable_steps);

    // ✅ Footer on LAST page only
    addFooter(doc);

    // ✅ Safe filename + download
    const safeName = sanitizeFilename(data.originalFilename || "resume-analysis");
    doc.save(`Resume-Analysis-${safeName}.pdf`);
    
  } catch (error) {
    console.error("PDF generation failed:", error);
    // Graceful fallback: alert user
    if (typeof window !== "undefined") {
      alert("Failed to generate PDF. Please try again or contact support.");
    }
  }
};

// ✅ JD MATCH PDF GENERATOR (Fixed)
export const generateJDMatchPDF = (data: JDMatch) => {
  try {
    // ✅ LOCAL state - no module-level mutation
    const doc = new jsPDF();
    const y = { current: 20 };

    // Header
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(17, 24, 39);
    doc.text("Resume vs Job Description Match Report", MARGIN, y.current);
    y.current += 10;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100);
    const jdLabel = data.jdTitle?.trim() || "Custom Job Description";
    doc.text(`Generated: ${new Date().toISOString().split("T")[0]} | JD: ${jdLabel}`, MARGIN, y.current);
    y.current += 6;
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const scoreColor = data.matchScore >= 80 ? [22, 163, 74] : data.matchScore >= 60 ? [202, 138, 4] : [220, 38, 38];
    doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
    doc.text(`Match Score: ${data.matchScore}%`, MARGIN, y.current);
    y.current += 14;

    // Analysis Sections
    addSectionTitle(doc, y, "Keyword Match", `Score: ${data.analysis.keyword_match.score}/100`);
    if (data.analysis.keyword_match.missing?.length) {
      addWrappedText(doc, y, `Missing: ${data.analysis.keyword_match.missing.join(", ")}`, 10, [220, 38, 38]);
    }

    addSectionTitle(doc, y, "Skills Alignment", `Score: ${data.analysis.skills_alignment.score}/100`);
    if (data.analysis.skills_alignment.gaps?.length) {
      addWrappedText(doc, y, `Gaps: ${data.analysis.skills_alignment.gaps.join(", ")}`, 10, [202, 138, 4]);
    }
    if (data.analysis.skills_alignment.matches?.length) {
      addBulletList(doc, y, data.analysis.skills_alignment.matches.slice(0, 8));
    }

    addSectionTitle(doc, y, "Experience Fit", `Score: ${data.analysis.experience_fit.score}/100`);
    addWrappedText(doc, y, data.analysis.experience_fit.feedback);

    addSectionTitle(doc, y, "Education Match", `Score: ${data.analysis.education_match.score}/100`);
    addWrappedText(doc, y, data.analysis.education_match.feedback);

    addSectionTitle(doc, y, "Tailored Interview Talking Points");
    addBulletList(doc, y, data.tailored_talking_points);

    addSectionTitle(doc, y, "Suggested Resume Improvements");
    addBulletList(doc, y, data.suggested_improvements);

    // ✅ Footer on LAST page only
    addFooter(doc);

    // ✅ Safe filename + download
    const safeName = sanitizeFilename(jdLabel);
    doc.save(`JD-Match-${safeName}.pdf`);
    
  } catch (error) {
    console.error("PDF generation failed:", error);
    if (typeof window !== "undefined") {
      alert("Failed to generate PDF. Please try again or contact support.");
    }
  }
};